CC98.Medal/src/CC98.Medal/Controllers/MedalController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using CC98.Identity;
using CC98.Medal.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Sakura.AspNetCore;
using Sakura.AspNetCore.Authentication;
using Sakura.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace CC98.Medal.Controllers
{
	/// <summary>
	/// 提供勋章相关功能。
	/// </summary>
	public class MedalController : Controller
	{
		public MedalController(MedalDataModel dataModel, CC98MainDataModel cc98DataModel, IOperationMessageAccessor messageAccessor, ExternalSignInManager externalSignInManager)
		{
			DataModel = dataModel;
			MessageAccessor = messageAccessor;
			ExternalSignInManager = externalSignInManager;
			CC98DataModel = cc98DataModel;
		}

		#region 注入对象

		/// <summary>
		/// 数据库连接对象。
		/// </summary>
		private MedalDataModel DataModel { get; }

		private CC98MainDataModel CC98DataModel { get; }

		/// <summary>
		/// 操作消息访问器。
		/// </summary>
		private IOperationMessageAccessor MessageAccessor { get; }

		/// <summary>
		/// 外部登录管理器。
		/// </summary>
		private ExternalSignInManager ExternalSignInManager { get; }

		#endregion

		#region 辅助方法

		/// <summary>
		/// 确保获得勋章，否则引发错误。
		/// </summary>
		/// <param name="id">勋章标识。</param>
		/// <returns>操作结果。</returns>
		private async Task<Data.Medal> EnsureGetMedalAsync(int id)
		{
			var item = await (from i in DataModel.Medals
							  where i.Id == id
							  select i).SingleOrDefaultAsync();

			if (item == null)
			{
				throw new ActionResultException(HttpStatusCode.NotFound);
			}

			return item;
		}

		#endregion

		/// <summary>
		/// 显示勋章主页。
		/// </summary>
		/// <returns>操作结果。</returns>
		[AllowAnonymous]
		public IActionResult Index(int page = 1)
		{
			var items = from i in DataModel.Medals.Include(p => p.Category)
						select i;

			return View(items.ToPagedList(20, page));
		}

		/// <summary>
		/// 创建新勋章。
		/// </summary>
		/// <returns>操作结果。</returns>
		[HttpGet]
		[Authorize(Policies.Edit)]
		public IActionResult Create()
		{
			return View();
		}

		/// <summary>
		/// 执行添加勋章操作。
		/// </summary>
		/// <param name="model">数据模型。</param>
		/// <returns>操作结果。</returns>
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Policies.Edit)]
		public async Task<IActionResult> Create(Data.Medal model)
		{
			HandleModel(model);


			if (ModelState.IsValid)
			{
				try
				{
					DataModel.Medals.Add(model);
					await DataModel.SaveChangesAsync();

					MessageAccessor.Messages.Add(OperationMessageLevel.Success, "操作成功。",
						string.Format(CultureInfo.CurrentUICulture, "你已经成功添加了勋章 {0}。", model.Name));

					return RedirectToAction("Index", "Medal");
				}
				catch (Exception ex)
				{
					ModelState.AddModelError(string.Empty, ex.Message);
				}
			}

			return View(model);
		}

		/// <summary>
		/// 编辑勋章信息。
		/// </summary>
		/// <param name="id">要编辑的勋章的标识。</param>
		/// <returns>操作结果。</returns>
		[HttpGet]
		[Authorize(Policies.Edit)]
		public async Task<IActionResult> Edit(int id)
		{
			return View(await EnsureGetMedalAsync(id));
		}

		/// <summary>
		/// 执行编辑操作。
		/// </summary>
		/// <param name="model">数据模型。</param>
		/// <returns>操作结果。</returns>
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Policies.Edit)]
		public async Task<IActionResult> Edit(Data.Medal model)
		{
			HandleModel(model);

			if (ModelState.IsValid)
			{
				try
				{
					DataModel.Medals.Update(model);
					await DataModel.SaveChangesAsync();

					MessageAccessor.Messages.Add(OperationMessageLevel.Success, "操作成功。",
						string.Format(CultureInfo.CurrentUICulture, "你已经成功修改了勋章 {0}。", model.Name));

					return RedirectToAction("Index", "Medal");
				}
				catch (Exception ex)
				{
					ModelState.AddModelError(string.Empty, ex.Message);
				}
			}

			return View(model);
		}

		/// <summary>
		/// 删除模型中重复项目导致的不必要数据更新信息。
		/// </summary>
		/// <param name="model">模型对象</param>
		private void HandleModel(Data.Medal model)
		{
			ModelState.Remove(nameof(model.Category));
		}

		/// <summary>
		/// 显示勋章详细信息。
		/// </summary>
		/// <param name="id">勋章的标识。</param>
		/// <returns>操作结果。</returns>
		[HttpGet]
		[AllowAnonymous]
		public async Task<IActionResult> Detail(int id)
		{
			return View(await EnsureGetMedalAsync(id));
		}

		/// <summary>
		/// 放弃勋章。
		/// </summary>
		/// <param name="id">要放弃的勋章的标识。</param>
		/// <returns>操作结果。</returns>
		[HttpPost]
		[Authorize]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Discard(int id)
		{
			var userId = User.GetId();

			var item = await (from i in DataModel.UserMedalIssues
							  where i.UserId == userId && i.MedalId == id
							  select i).SingleOrDefaultAsync();

			if (item == null)
			{
				return BadRequest("你目前没有获得这个勋章。");
			}


			// 删除并勋章记录
			DataModel.UserMedalIssues.Remove(item);
			await DataModel.SaveChangesAsync();

			return Ok();
		}

		/// <summary>
		/// 申请勋章。
		/// </summary>
		/// <param name="id">要申请的勋章的标识。</param>
		/// <returns>操作结果。</returns>
		[HttpPost]
		[Authorize]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Apply(int id)
		{
			var userId = User.GetId();

			// 申请记录
			var hasApplied = await (from i in DataModel.UserMedalApplies
									where i.UserId == userId && i.MedalId == id
									select i).AnyAsync();

			if (hasApplied)
			{
				return BadRequest("你已经申请了这个勋章。");
			}

			// 拥有记录
			var hasOwnedInfinitily = await (from i in DataModel.UserMedalIssues
											where i.UserId == userId && i.MedalId == id && i.ExpireTime == null
											select i).AnyAsync();

			if (hasOwnedInfinitily)
			{
				return BadRequest("你已经无限期拥有该勋章，无需申请勋章。");
			}

			// 申请检查
			var medal = await EnsureGetMedalAsync(id);
			if (!medal.CanApply)
			{
				return BadRequest("管理员不允许申请该勋章。");
			}
			// 保存记录
			var item = new UserMedalApply { MedalId = id, UserId = userId, Time = DateTimeOffset.Now };
			DataModel.UserMedalApplies.Add(item);

			try
			{
				await DataModel.SaveChangesAsync();
			}
			catch (DbUpdateException ex)
			{
				return BadRequest(ex.Message);
			}

			return Ok();
		}


		/// <summary>
		/// 取消申请勋章。
		/// </summary>
		/// <param name="id">要取消申请的勋章的标识。</param>
		/// <returns>操作结果。</returns>
		[HttpPost]
		[Authorize]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Unapply(int id)
		{
			var userId = User.GetId();

			// 申请记录
			var item = await (from i in DataModel.UserMedalApplies
							  where i.UserId == userId && i.MedalId == id
							  select i).SingleOrDefaultAsync();

			// 未申请
			if (item == null)
			{
				return BadRequest("你尚未申请这个勋章。");
			}

			// 删除记录
			DataModel.UserMedalApplies.Remove(item);
			try
			{
				await DataModel.SaveChangesAsync();
			}
			catch (DbUpdateException ex)
			{
				return BadRequest(ex.Message);
			}

			return Ok();
		}

		/// <summary>
		/// 执行订购操作。
		/// </summary>
		/// <param name="id">勋章名称。</param>
		/// <param name="type">订购类型。</param>
		/// <returns>操作结果。</returns>
		[HttpPost]
		[Authorize]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Order(int id, int type)
		{

			var item = await (from i in DataModel.Medals
							  where i.Id == id
							  select i).SingleOrDefaultAsync();

			if (item == null)
			{
				return BadRequest("勋章不存在。");
			}

			if (item.PriceSettings.Length <= type)
			{
				return BadRequest("订购类型错误。");
			}

			var priceSetting = item.PriceSettings[type];

			var userId = User.GetId();
			var userName = ExternalSignInManager.GetUserName(User);

			// 提取旧版数据库的用户信息，如果无法找到则是一种异常情况
			var cc98UserInfo = await (from i in CC98DataModel.Users
									  where i.Name == userName
									  select i).SingleAsync();

			// 财富不够
			if (cc98UserInfo.Wealth < priceSetting.Price)
			{
				MessageAccessor.Messages.Add(OperationMessageLevel.Error, "购买勋章失败。", "您没有足够的财富值执行本次购买。");
				return RedirectToAction("Index", "Medal", new { id });
			}


			// 减少财富值
			cc98UserInfo.Wealth -= priceSetting.Price;
			await CC98DataModel.SaveChangesAsync();

			// TODO: 事务支持
			var orderItem = await (from i in DataModel.UserMedalIssues
								   where i.UserId == userId && i.MedalId == id
								   select i).SingleOrDefaultAsync();


			// 是否有现有的购买记录
			if (orderItem == null)
			{
				// 无购买记录时，创建一个新的购买记录，过期日期为今天
				orderItem = new UserMedalIssue
				{
					MedalId = id,
					UserId = userId,
					ExpireTime = DateTime.Today
				};
			}

			// 无限期不能继续购买
			if (orderItem.ExpireTime == null)
			{
				MessageAccessor.Messages.Add(OperationMessageLevel.Error, "购买勋章失败。", "您已经无限期拥有该勋章，无法再次购买勋章。");
				return RedirectToAction("Index", "Medal", new { id });
			}

			// 无限期购买
			if (priceSetting.ExpiryDate == null)
			{
				orderItem.ExpireTime = null;
			}
			// 有限期购买
			else
			{
				orderItem.ExpireTime += TimeSpan.FromDays(priceSetting.ExpiryDate.Value);
			}


			// 订购后返回该勋章主页
			return RedirectToAction("Index", "Medal", new { id });
		}
	}
}

CC98.Medal/src/CC98.Medal/ViewComponents/MedalCategoryListViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CC98.Medal.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CC98.Medal.ViewComponents
{
	/// <summary>
	/// 显示勋章分类列表的视图组件。
	/// </summary>
	public class MedalCategoryListViewComponent : ViewComponent
	{
		public MedalCategoryListViewComponent(MedalDataModel dataModel)
		{
			DataModel = dataModel;
		}

		/// <summary>
		/// 数据库连接对象。
		/// </summary>
		private MedalDataModel DataModel { get; }

		/// <summary>
		/// 异步执行调用。
		/// </summary>
		/// <returns>表示操作结果的异步任务。</returns>
		public async Task<IViewComponentResult> InvokeAsync()
		{
			var items = from i in DataModel.MedalCategories
						orderby i.Name ascending
						select i;

			return View(await items.ToArrayAsync());
		}
	}
}

CC98.Medal/src/CC98.Medal/ViewComponents/MedalCategorySelectorViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CC98.Medal.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CC98.Medal.ViewComponents
{
	public class MedalCategorySelectorViewComponent : ViewComponent
	{
		public MedalCategorySelectorViewComponent(MedalDataModel dataModel)
		{
			DataModel = dataModel;
		}

		/// <summary>
		/// 数据库连接对象。
		/// </summary>
		private MedalDataModel DataModel { get; }

		/// <summary>
		/// 显示勋章分类选择列表，选择器使用给定的名称作为字段名。
		/// </summary>
		/// <param name="modelName">字段名。</param>
		/// <returns>操作结果。</returns>
		public async Task<IViewComponentResult> InvokeAsync(string modelName)
		{
			var items = from i in DataModel.MedalCategories
						select i;

			ViewBag.ModelName = modelName;

			return View(await items.ToArrayAsync());
		}
	}
}

CC98.Medal/src/CC98.Medal/Views/Medal/Create.cshtml
@model Medal
@{
	ViewBag.PageTitle = "添加勋章";
}

<form asp-controller="Medal" asp-action="Create" method="post" asp-antiforgery="true">

	@await Html.PartialAsync("_EditPartial")

	<hr/>
	<div asp-validation-summary="ModelOnly" class="text-danger"></div>
	<button type="submit" class="btn btn-default btn-primary">确认添加</button>
	<button type="reset" class="btn btn-default">清空填写</button>

</form>

@await Html.PartialAsync("_UploadFilePartial")

CC98.Medal/src/CC98.Medal/Views/Medal/Detail.cshtml
@using System.Globalization
@using System.Threading.Tasks
@using Sakura.AspNetCore.Authentication
@inject ExternalSignInManager ExternalSignInManager

@model Medal
@{
	ViewBag.PageTitle = string.Format(CultureInfo.CurrentUICulture, "{0} - 勋章详情", Model.Name);
}
<div class="row">
    <div class="col-md-8">
        <div class="media">
            <div class="media-left media-heading">
                <img src="http://file.cc98.org/Medals/d4gdsj2t.gif" alt="勋章图像" style="padding:25px 30px;margin:20px ;border:1px solid LightBlue" />
            </div>
            <div class="media-body" style="padding:15px 25px">
                <p class="h4"><strong>勋章描述</strong></p>
                @if (!string.IsNullOrEmpty(Model.Description))
                {
                    <p>@Model.Description</p>
                }
                else
                {
                    <p class="text-muted text-center">该勋章没有提供描述</p>
                }
                <br />
                @if (!string.IsNullOrEmpty(Model.Link))
                {

                    <a class="btn btn-default " href="@Model.Link">访问该勋章关联的网页</a>
                    
                }

                
            </div>
        </div>
        <hr />

		<div style="margin-left: auto;margin-right: auto;display: table;width: auto;padding-top:20px;">
			@if (ExternalSignInManager.IsSignedIn(User))
			{

				if (Model.CanApply)
				{
					<button type="button" class="btn btn-info" style="margin:10px">申请勋章</button> }

				if (Model.PriceSettings.Length > 0)
				{
					<div class="btn-group">
						<button type="button" class="btn btn-default btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="margin:10px">
							购买勋章 <span class="caret"></span>
						</button>
						<ul class="dropdown-menu">

							@for (var index = 0; index < Model.PriceSettings.Length; index++)
							{
								var item = Model.PriceSettings[index];

								var displayText =
									item.ExpiryDate == null
										? string.Format(CultureInfo.CurrentUICulture, "永久有效，价格 {0}", item.Price)
										: string.Format(CultureInfo.CurrentUICulture, "{0} 天有效，价格 {1}", item.ExpiryDate.Value, item.Price);

								<li>
									<a href="#" onclick="showOrderDialog(this);" data-type="@index" data-name="@Model.Name" data-price="@item.Price" data-days="@item.ExpiryDate">@displayText</a>
								</li>
							}
						</ul>
					</div> }

				if (!Model.CanApply && Model.PriceSettings.Length == 0)
				{
					<p class="text-center text-muted">这个勋章只能由管理员颁发。如果你希望获得它，请联系管理员。</p> }

				<form asp-controller="Medal" asp-action="Order" asp-route-id="@Model.Id" method="post" asp-antiforgery="true" data-ajax="true" data-ajax-success="" data-ajax-failure="onAjaxError(this, xhr);">

					<input type="hidden" name="type" id="order-type-input" />

					<div class="modal fade" id="order-medal-dialog">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
									<h4 class="modal-title">购买勋章</h4>
								</div>
								<div class="modal-body">
									<p>
										你即将购买勋章 <strong id="order-medal-name-text"></strong>。本次购买需要花费 <strong id="order-medal-price-text"></strong> 财富值，有效期为 <strong id="order-medal-days-text"></strong>。
									</p>
									<p class="text-info">购买勋章后，你将立即获得该勋章并扣除对应的财富值。如果你之前已经购买了该勋章，则本次购买有效期将和勋章的现有剩余有效天数叠加。如果你已经申请了该勋章且本次购买为永久有效，则申请将自动撤销。</p>
									<p>
										如果你确定要执行购买操作，请单击<q>确认购买</q>按钮。否则请单击<q>关闭</q>或对话框外的任意位置。
									</p>
								</div>
								<div class="modal-footer">
									<p class="dialog-error text-danger"></p>
									<button type="submit" class="btn btn-primary">确认购买</button>
									<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
								</div>
							</div><!-- /.modal-content -->
						</div><!-- /.modal-dialog -->
					</div><!-- /.modal -->
				</form>
			}
			else
			{
				<p class="text-muted text-center">如果你想要申请或者购买这个勋章，请先<a asp-controller="Account" asp-action="LogOn" asp-route-returnUrl="@Url.Action()">登录</a>后再访问这里</p>
			}
		</div>
        
    </div>
    <div class="col-md-4" style="border-left:1px solid #ccc;padding:15px">
        <h4>Auser</h4>
        <p class="h5">我的财富值：888888</p>
		<p class="h5">我的权限：普通用户</p>
        <hr />
		
        <h4>已购买的勋章</h4>
        
        <img src="http://file.cc98.org/Medals/d4gdsj2t.gif" alt="勋章图像" style="margin:10px;" />有效期：13天<br />
        <img src="http://file.cc98.org/Medals/d4gdsj2t.gif" alt="勋章图像" style="margin:10px;" />有效期：13天<br />
        <img src="http://file.cc98.org/Medals/d4gdsj2t.gif" alt="勋章图像" style="margin:10px;" />有效期：13天<br />
        <a>>>查看全部</a>
    </div>

</div>
@section scripts{

	<script type="text/javascript" language="javascript">

		function showOrderDialog(btn) {

			$('#order-medal-name-text').text($(btn).data('name'));
			$('#order-medal-price-text').text($(btn).data('price'));
			$('#order-medal-days-text').text($(btn).data('days'));

			$('#order-type-input').val($(btn).data('type'));

			$('#order-medal-dialog').modal();
		}

		function onAjaxError(dialog, xhr) {
			$(dialog).find('.dialog-error').text(xhr.responseText);
		}

	</script>

}

CC98.Medal/src/CC98.Medal/Views/Medal/Edit.cshtml
@using System.Globalization
@model Medal
@{
	ViewBag.PageTitle = string.Format(CultureInfo.CurrentUICulture, "编辑勋章 - {0}", Model.Name);
}

<form asp-controller="Medal" asp-action="Edit" method="post" asp-antiforgery="true">

	@await Html.PartialAsync("_EditPartial")

	<hr/>
	<div asp-validation-summary="ModelOnly" class="text-danger"></div>
	<button type="submit" class="btn btn-default btn-primary">确认修改</button>
	<button type="reset" class="btn btn-default">撤销更改</button>

</form>

@await Html.PartialAsync("_UploadFilePartial")

CC98.Medal/src/CC98.Medal/Views/Medal/Index.cshtml
@using Microsoft.AspNetCore.Authorization
@model IPagedList<Medal>
@inject IAuthorizationService AuthorizationService
@{
	ViewBag.PageTitle = "勋章列表";

	var canAdmin = true;
}

<div class="row">
	<div class="col-md-2">
		@await Component.InvokeAsync("MedalCategoryList")
	</div>
	<div class="col-md-10">
		@if (Model.Any())
		{
			<div class="row">
				@foreach (var i in Model)
				{
					<div class="col-md-4 col-sm-6 col-xs-12">
						<div class="thumbnail">
							<div class="media">
                               
								<div class="media-left media-middle">
									<img src="@i.ImageUri" alt="勋章图像" title="@i.Description" style="padding:15px 25px;margin:10px;border:1px solid LightBlue"/>
								</div>
								<div class="media-body">
									
                                    <p class="h5">
                                        <a asp-controller="Medal" asp-action="Detail" asp-route-id="@i.Id"><strong>@i.Name&nbsp;</strong></a>
                                        <small>
                                            <span>
                                                <a asp-controller="Medal" asp-action="Edit" asp-route-id="@i.Id" title="编辑该勋章的信息"><span class="glyphicon glyphicon-pencil"></span></a>
                                                <a asp-controller="Medal" asp-action="Delete" asp-route-id="@i.Id" title="删除该勋章"><span class="glyphicon glyphicon-remove"></span></a>
                                            </span>
                                        </small>

                                    </p>
									<p class="h6"style="text-indent:1em">$5000</p>
									<p class="h4">
										@if (i.CanApply)
										{
											<span class="label label-info">可申请</span>
										}
										@if (i.PriceSettings.Length > 0)
										{
											<span class="label label-success">可购买</span>
										}
										@if (!i.CanApply && i.PriceSettings.Length == 0)
										{
											<span class="label label-warning">仅颁发</span>
										}
									</p>
								</div>
                                
                                <p class="help-block" style="border-top:1px solid #ddd;padding:10px">@i.Description</p>
							</div>
						</div>
					</div>
				}
			</div>
		}
		else
		{
			<p class="text-center text-muted">目前没有可以显示的勋章</p>
		}
	</div>
</div>

<hr />
<a asp-controller="Medal" asp-action="Create" class="btn btn-default btn-primary">添加新勋章</a>

CC98.Medal/src/CC98.Medal/Views/Medal/_EditPartial.cshtml
@model Medal

<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default panel-primary">
			<div class="panel-heading">
				<h2 class="panel-title">勋章信息</h2>
			</div>
			<div class="panel-body">
				<div class="form-group">
					<label asp-for="Name" class="control-label">勋章名称</label>
					<input type="text" asp-for="Name" class="form-control" />
					<span asp-validation-for="Name" class="text-danger"></span>
					<p class="help-block">勋章的名称将会出现在提示和列表界面中。</p>
				</div>

				<div class="form-group">
					<label asp-for="Description" class="control-label">勋章描述</label>
					<textarea type="text" asp-for="Description" class="form-control" rows="3"></textarea>
					<span asp-validation-for="Description" class="text-danger"></span>
					<p class="help-block">勋章的描述将会出现在鼠标悬停界面中。</p>
				</div>

				<div class="form-group">
					<label asp-for="CategoryId" class="control-label">勋章分类</label>
					@await Component.InvokeAsync("MedalCategorySelector", new { modelName = nameof(Model.CategoryId) })
					<span asp-validation-for="CategoryId" class="text-danger"></span>
					<p class="help-block">选择勋章所属的类别，这可方便用户更容易找到勋章。</p>
				</div>

				<div class="form-group">
					<label asp-for="ImageUri" class="control-label">图片地址</label>
					<div class="input-group">
						<input id="image-uri-input" type="url" asp-for="ImageUri" class="form-control" />
						<span class="input-group-btn">
							<button type="button" class="btn btn-default" onclick="uploadMedalImage();">上传图片</button>
						</span>
					</div>
					<span id="image-uri-error-span" asp-validation-for="ImageUri" class="text-danger"></span>
					<p class="help-block">勋章图片的地址。支持所有浏览器常见格式。</p>
				</div>

				<div class="form-group">
					<label asp-for="Link" class="control-label">链接地址</label>
					<input type="url" asp-for="Link" class="form-control" />
					<span asp-validation-for="Link" class="text-danger"></span>
					<p class="help-block">单击勋章时跳转到的链接地址。如不填写则默认跳转到勋章中心。</p>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-6">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h2 class="panel-title">颁发设置</h2>
			</div>
			<div class="panel-body">
				<p class="help-block">在下方可设置用户获得勋章的途径。注意：具有操作员或者更高级别权限的用户始终可以手动授予用户任意勋章，并设定授予的有效期限。</p>
				<hr />
				<div class="checkbox">
					<label>
						<input type="checkbox" asp-for="CanApply" /> 允许用户申请该勋章
					</label>
					<span asp-validation-for="CanApply" class="text-danger"></span>
					<p class="help-block">如果选中该复选框，则用户可以通过勋章中心申请勋章并由审核员进行审核。申请勋章无需支付论坛货币。</p>
				</div>

				<hr />

				<div class="form-group">

					<p class="help-block">下表列出了该勋章的所有购买选项。你可以为不同的有效时间分别设定价格。如果列表中没有任何项目，则用户将不能通过支付论坛货币的形式获得勋章。</p>

					@{
						// 价格数量
						var priceCount = Model?.PriceSettings?.Length ?? 0;
					}


					<table class="table">
						<thead>
							<tr>
								<th>时间（天）</th>
								<th>价格</th>
								<th>操作</th>
							</tr>
						</thead>
						<tbody id="price-table">
							@for (var i = 0; i < priceCount; i++)
							{
								<tr>
									<td><input type="number" step="1" min="0" asp-for="PriceSettings[i].ExpiryDate" placeholder="永不过期" class="form-control input-sm" /></td>
									<td><input type="number" step="1" min="0" asp-for="PriceSettings[i].Price" class="form-control input-sm" /></td>
									<td><button type="button" class="btn btn-sm btn-danger" onclick="deletePriceItem(this);">删除</button></td>
								</tr>
							}

							<tr>
								<td><input type="number" step="1" min="0" placeholder="永不过期" class="form-control input-sm" /></td>
								<td><input type="number" step="1" min="0" class="form-control input-sm" /></td>
								<td><button type="button" class="btn btn-sm btn-success" onclick="addPriceItem(this);">添加</button></td>
							</tr>
						</tbody>
					</table>

				</div>

			</div>
		</div>
	</div>

</div>

<script type="text/javascript" language="javascript">

	function deletePriceItem(btn) {

		$(btn).parents('tr').first().remove();

		// 重排所有内容
		reapplyPriceItems();

	}

	function reapplyPriceItems() {

		$('#price-table').find('tr').each(function (index, ele) {
			$(ele).find('input').eq(0).prop('name', 'PriceSettings[' + index + '].ExpiryDate');
			$(ele).find('input').eq(1).prop('name', 'PriceSettings[' + index + '].Price');
		});
	}

	function addPriceItem(btn) {

		// 当前行
		var row = $(btn).parents('tr').first();

		var clone = $(row).clone();
		// 清除所有内容
		$(clone).find('input').val('');

		// 修改上一行样式
		$(row).find('button').text('删除');
		$(row).find('button').removeClass('btn-success').addClass('btn-danger');
		$(row).find('button').attr('onclick', 'deletePriceItem(this);');

		// 重排所有内容
		reapplyPriceItems();

		$('#price-table').append(clone);
	}

	function onUploadImageSuccess(data) {
		$('#image-uri-input').val(data);
	}

	function onUploadImageFail() {
		$('#image-uri-error-span').text('上传时发生错误，请再试一次。');
	}

	function uploadMedalImage() {
		requestUpload(onUploadImageSuccess, onUploadImageFail);
	}

</script>