CC98.Medal/src/CC98.Medal/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.Editor;
using Microsoft.Extensions.FileProviders;
using Microsoft.Extensions.Options;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace CC98.Medal.Controllers
{
	/// <summary>
	/// 提供文件服务。
	/// </summary>
	public class FileController : Controller
	{
		public FileController(IOptions<AppSetting> appSetting)
		{
			AppSetting = appSetting.Value;
		}

		private AppSetting AppSetting { get; }

		/// <summary>
		/// 提供上传文件服务。
		/// </summary>
		/// <param name="file">上传的文件。</param>
		/// <returns>操作结果。</returns>
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Policies.Edit)]
		public async Task<IActionResult> Upload(IFormFile file)
		{
			// 随机名称，保持原有后缀
			var randomName = Path.ChangeExtension(Path.GetRandomFileName(), Path.GetExtension(file.FileName));
			var storePath = Path.Combine(AppSetting.MedalImageStoreFolder, randomName);
			var displayPath = new PathString(AppSetting.MedalImagePath) + new PathString("/" + randomName);

			using (var stream = System.IO.File.OpenWrite(storePath))
			{
				try
				{
					await file.CopyToAsync(stream);
					return Ok(displayPath.ToString());
				}
				catch
				{
					// ignored
				}
			}

			return BadRequest();

		}
	}
}

CC98.Medal/src/CC98.Medal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - CC98 勋章中心</title>

	<environment names="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/css/site.css" />
	</environment>
	<environment names="Staging,Production">
		<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
			  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
		<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
	</environment>
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">切换导航栏</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a asp-controller="Home" asp-action="Index" class="navbar-brand">CC98 勋章中心</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a asp-controller="Medal" asp-action="Index">勋章列表</a></li>
					<li><a asp-controller="Home" asp-action="Index">主页</a></li>
					<li><a asp-controller="Home" asp-action="About">关于</a></li>
					<li><a asp-controller="Home" asp-action="Contact">联系我们</a></li>
				</ul>
				@await Html.PartialAsync("_LogOnPartial")
			</div>
		</div>
	</div>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; 2016 - CC98</p>
		</footer>
	</div>

	<environment names="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
		<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
		<script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
		<script src="~/lib/jquery-form/jquery.form.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
	</environment>
	<environment names="Staging,Production">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery">

		</script>

		<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"
				asp-fallback-src="~/lib/jquery-validation/dist/jquery.validate.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.validate">

		</script>


		<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
		<script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
		<script src="~/lib/jquery-form/jquery.form.js"></script>

		<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
		</script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>

	@RenderSection("scripts", false)
</body>
</html>

CC98.Medal/src/CC98.Medal/Views/Shared/_LogOnPartial.cshtml
@using System.Threading.Tasks
@using Sakura.AspNetCore.Authentication
@inject ExternalSignInManager ExternalSignInManager

<ul class="nav navbar-nav navbar-right">
	@if (ExternalSignInManager.IsSignedIn(User))
	{
		<li><a asp-controller="Account" asp-action="Detail"><strong>@ExternalSignInManager.GetUserName(User)</strong></a></li>
		<li><a href="#" onclick="$('#logoff-form').submit();">注销</a></li>
	}
	else
	{
		<li><a asp-controller="Account" asp-action="LogOn" asp-route-returnUrl="@Url.Action()">登录</a></li>
	}
</ul>

<form class="hidden" asp-controller="Account" asp-action="LogOff" asp-antiforgery="true" id="logoff-form"></form>

CC98.Medal/src/CC98.Medal/Views/Shared/_StandardTitleLayout.cshtml
@{
    // 如果没有定义窗口标题，则使用页面标题作为窗口标题
    if (ViewBag.Title == null)
    {
        ViewBag.Title = ViewBag.PageTitle;
    }

    Layout = "_Layout";
}

<h1 class="page-header lead text-center">@ViewBag.PageTitle</h1>

@* 如果没有禁止显示消息，则默认显示消息 *@
@if (ViewBag.ShowOperationMessages != false)
{
    <div asp-message-list="AlertDialogClosable"></div>
}

@RenderBody()

@section scripts{
    @await RenderSectionAsync("scripts", false);
}

CC98.Medal/src/CC98.Medal/Views/Shared/_UploadFilePartial.cshtml
<form id="upload-file-form" asp-controller="File" asp-action="Upload" asp-antiforgery="true" enctype="multipart/form-data">
	<input id="upload-file-input" type="file" name="file" accept="image/*" class="hidden" />
</form>

<script type="text/javascript" language="javascript">

	function requestUpload(successFunc, errorFunc) {

		$('#upload-file-input').change(function () {

			$('#upload-file-form').ajaxSubmit({
				success: successFunc,
				error: errorFunc
			});
		});

		$('#upload-file-input').click();
	}

</script>